# ==========================================
# CONFIGURACIÓN DE SERVIDOR
# ==========================================
server.port=8080

# ==========================================
# CONFIGURACIÓN DE CONEXIÓN A POSTGRESQL (UNIVERSAL)
# ==========================================
# Nos conectamos a 'template1' (BD base de Postgres) para asegurar acceso inicial rápido
spring.datasource.url=jdbc:postgresql://localhost:5432/template1
# Credenciales estándar universales de laboratorios y entornos locales
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# ESTRATEGIA DE JPA / HIBERNATE
# ==========================================
# 'update' se encarga de crear o actualizar las tablas automáticamente según tus entidades de Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Fuerza a Spring Boot a ejecutar el archivo data.sql para poblar registros iniciales
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
