# ==========================================
# CONFIGURACIÓN DE SERVIDOR
# ==========================================
server.port=8080

# ==========================================
# CONFIGURACIÓN DE CONEXIÓN A POSTGRESQL (UNIVERSAL)
# ==========================================
# Apuntamos a 'almacen_db' porque nuestro código Java ya garantizó su creación física al arrancar
spring.datasource.url=jdbc:postgresql://localhost:5432/almacen_db
# Credenciales estándar universales de laboratorios y entornos locales
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# ESTRATEGIA DE JPA / HIBERNATE
# ==========================================
# 'update' se encarga de crear las tablas automáticamente según tus entidades de Java dentro de almacen_db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Fuerza a Spring Boot a ejecutar el archivo data.sql para poblar registros iniciales
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
