# ==========================================
# CONFIGURACIÓN DE SERVIDOR
# ==========================================
server.port=8080

# ==========================================
# CONFIGURACIÓN DE CONEXIÓN A POSTGRESQL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/almacen_db
spring.datasource.username=postgres
spring.datasource.password=alonsolmz
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# ESTRATEGIA DE JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Fuerza a Spring Boot a ejecutar el data.sql después de crear las tablas
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
